### ISSUE TITLE
Put a link to this repository on rlsd2.dimakrasner.com

### ISSUE THREAD

**Issue by dbohdan** [dimkr/rlsd2#2]
Somewhat confusingly, http://rlsd2.dimakrasner.com/ currently features links to RLSD's components (packlim, luufs, etc.) but not to the distro itself.

**Comment by dimkr** [comment]
I guess I should move the link up :)

**Comment by dbohdan** [comment]
Sorry, I wasn't clear: I meant a link to https://github.com/dimkr/rlsd2/ specifically. I could not find one visually on the page or by grepping the source code. I _have_ noticed the link to git://rlsd2.dimakrasner.com/.
